objects:=*.out *.o
GCCFLAGS:=-Wall -W -O2

sum2: sum2.c
	gcc -o sum2.out ${GCCFLAGS} sum2.c
length: length.c
	gcc -o length.out ${GCCFLAGS} length.c
length2: length2.c
	gcc -o length2.out ${GCCFLAGS} length2.c
Ex_7_1: Ex_7_1.c
	gcc -o Ex_7_1.out ${GCCFLAGS} Ex_7_1.c
Ex_7_14: Ex_7_14.c
	gcc -o Ex_7_14.out ${GCCFLAGS} Ex_7_14.c
Code_7_1: Code_7_1.c
	gcc -o Code_7_1.out ${GCCFLAGS} Code_7_1.c
Code_7_2: Code_7_2.c
	gcc -o Code_7_2.out ${GCCFLAGS} Code_7_2.c
Code_7_3: Code_7_3.c
	gcc -o Code_7_3.out ${GCCFLAGS} Code_7_3.c
Code_7_4: Code_7_4.c
	gcc -o Code_7_4.out ${GCCFLAGS} Code_7_4.c
Code_7_5: Code_7_5.c
	gcc -o Code_7_5.out ${GCCFLAGS} Code_7_5.c
Code_7_6: Code_7_6.c
	gcc -o Code_7_6.out ${GCCFLAGS} Code_7_6.c
Code_7_7: Code_7_7.c
	gcc -o Code_7_7.out ${GCCFLAGS} Code_7_7.c
Code_7_8: Code_7_8.c
	gcc -o Code_7_8.out ${GCCFLAGS} Code_7_8.c
Code_7_10: Code_7_10.c
	gcc -o Code_7_10.out ${GCCFLAGS} Code_7_10.c
Code_7_11: Code_7_11.c
	gcc -o Code_7_11.out ${GCCFLAGS} Code_7_11.c
Code_7_12: Code_7_12.c
	gcc -o Code_7_12.out ${GCCFLAGS} Code_7_12.c 
Code_7_13: Code_7_13.c
	gcc -o Code_7_13.out ${GCCFLAGS} Code_7_13.c
Code_7_14: Code_7_14.c
	gcc -o Code_7_14.out ${GCCFLAGS} Code_7_14.c
Code_7_15: Code_7_15.c
	gcc -o Code_7_15.out ${GCCFLAGS} Code_7_15.c





.PHONY : clean
clean:
	-rm edit $(objects)
