objects:=*.out *.o *.so
GCCFALG:=-Wall -W -O2

26_1: 26_1.c
	gcc -o 26_1.out ${GCCFALG} 26_1.c
tnumconv: tnumconv.c
	gcc -o tnumconv.out ${GCCFALG} tnumconv.c
trand: trand.c
	gcc -o trand.out ${GCCFALG} trand.c
airmiles: airmiles.c
	gcc -o airmiles.out ${GCCFALG} airmiles.c
datetime: datetime.c
	gcc -o datetime.out ${GCCFALG} datetime.c
Ex_26_1: Ex_26_1.c
	gcc -o Ex_26_1.out ${GCCFALG} Ex_26_1.c
Ex_26_2: Ex_26_2.c
	gcc -o Ex_26_2.out ${GCCFALG} Ex_26_2.c
Ex_26_3: Ex_26_3.c
	gcc -o Ex_26_3.out ${GCCFALG} Ex_26_3.c
Ex_26_4: Ex_26_4.c
	gcc -o Ex_26_4.out ${GCCFALG} Ex_26_4.c
Ex_26_5: Ex_26_5.c
	gcc -o Ex_26_5.out ${GCCFALG} Ex_26_5.c
Ex_26_6: Ex_26_6.c
	gcc -o Ex_26_6.out ${GCCFALG} Ex_26_6.c
Ex_26_9: Ex_26_9.c
	gcc -o Ex_26_9.out ${GCCFALG} Ex_26_9.c
Ex_26_12: Ex_26_12.c
	gcc -o Ex_26_12.out ${GCCFALG} Ex_26_12.c
Code_26_1: Code_26_1.c
	gcc -o Code_26_1.out ${GCCFALG} Code_26_1.c
Code_26_2: Code_26_2.c
	gcc -o Code_26_2.out ${GCCFALG} Code_26_2.c
Code_26_3: Code_26_3.c
	gcc -o Code_26_3.out ${GCCFALG} Code_26_3.c
Code_26_4: Code_26_4.c
	gcc -o Code_26_4.out ${GCCFALG} Code_26_4.c
Code_26_5: Code_26_5.c
	gcc -o Code_26_5.out ${GCCFALG} Code_26_5.c
Code_26_6: Code_26_6.c
	gcc -o Code_26_6.out ${GCCFALG} Code_26_6.c



.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done


