objects:=*.out *.o
GCCFLAGS:=-Wall -W -O2

square: square.c
	gcc -o square.out ${GCCFLAGS} square.c
sum: sum.c
	gcc -o sum.out ${GCCFLAGS} sum.c
numdigit: numdigit.c
	gcc -o numdigit.out ${GCCFLAGS} numdigit.c
square2: square2.c
	gcc -o square2.out ${GCCFLAGS} square2.c
square3: square3.c
	gcc -o square3.out ${GCCFLAGS} square3.c
checking: checking.c
	gcc -o checking.out ${GCCFLAGS} checking.c
Ex_6_123: Ex_6_123.c
	gcc -o Ex_6_123.out ${GCCFLAGS} Ex_6_123.c
Ex_6_67: Ex_6_67.c
	gcc -o Ex_6_67.out ${GCCFLAGS} Ex_6_67.c
Ex_6_89: Ex_6_89.c
	gcc -o Ex_6_89.out ${GCCFLAGS} Ex_6_89.c
Ex_6_11: Ex_6_11.c
	gcc -o Ex_6_11.out ${GCCFLAGS} Ex_6_11.c
Ex_6_12: Ex_6_12.c
	gcc -o Ex_6_12.out ${GCCFLAGS} Ex_6_12.c
Ex_6_1314: Ex_6_1314.c
	gcc -o Ex_6_1314.out ${GCCFLAGS} Ex_6_1314.c
Code_6_1: Code_6_1.c
	gcc -o Code_6_1.out ${GCCFLAGS} Code_6_1.c
Code_6_2: Code_6_2.c
	gcc -o Code_6_2.out ${GCCFLAGS} Code_6_2.c
Code_6_3: Code_6_3.c
	gcc -o Code_6_3.out ${GCCFLAGS} Code_6_3.c
Code_6_4: Code_6_4.c
	gcc -o Code_6_4.out ${GCCFLAGS} Code_6_4.c
Code_6_5: Code_6_5.c
	gcc -o Code_6_5.out ${GCCFLAGS} Code_6_5.c
Code_6_6: Code_6_6.c
	gcc -o Code_6_6.out ${GCCFLAGS} Code_6_6.c
Code_6_7: Code_6_7.c
	gcc -o Code_6_7.out ${GCCFLAGS} Code_6_7.c
Code_6_8: Code_6_8.c
	gcc -o Code_6_8.out ${GCCFLAGS} Code_6_8.c
Code_6_10: Code_6_10.c
	gcc -o Code_6_10.out ${GCCFLAGS} Code_6_10.c
Code_6_11: Code_6_11.c
	gcc -o Code_6_11.out ${GCCFLAGS} Code_6_11.c
Code_6_12: Code_6_12.c
	gcc -o Code_6_12.out ${GCCFLAGS} Code_6_12.c









.PHONY : clean
clean:
	-rm edit $(objects)
