objects:=*.out *.o
GCCFLAG:=-Wall -W -O2

broker: broker.c
	gcc -o broker.out ${GCCFLAG} broker.c
date: date.c
	gcc -o date.out ${GCCFLAG} date.c
Ex_5_1: Ex_5_1.c
	gcc -o Ex_5_1.out ${GCCFLAG} Ex_5_1.c	
Ex_5_2: Ex_5_2.c
	gcc -o Ex_5_2.out ${GCCFLAG} Ex_5_2.c	
Ex_5_3: Ex_5_3.c
	gcc -o Ex_5_3.out ${GCCFLAG} Ex_5_3.c	
Ex_5_7: Ex_5_7.c
	gcc -o Ex_5_7.out ${GCCFLAG} Ex_5_7.c	
Ex_5_11: Ex_5_11.c
	gcc -o Ex_5_11.out ${GCCFLAG} Ex_5_11.c	
Code_5_1: Code_5_1.c
	gcc -o Code_5_1.out ${GCCFLAG} Code_5_1.c
Code_5_2: Code_5_2.c
	gcc -o Code_5_2.out ${GCCFLAG} Code_5_2.c
Code_5_3: Code_5_3.c
	gcc -o Code_5_3.out ${GCCFLAG} Code_5_3.c
Code_5_4: Code_5_4.c
	gcc -o Code_5_4.out ${GCCFLAG} Code_5_4.c
Code_5_5: Code_5_5.c
	gcc -o Code_5_5.out ${GCCFLAG} Code_5_5.c
Code_5_6: Code_5_6.c
	gcc -o Code_5_6.out ${GCCFLAG} Code_5_6.c
Code_5_7: Code_5_7.c
	gcc -o Code_5_7.out ${GCCFLAG} Code_5_7.c
Code_5_8: Code_5_8.c
	gcc -o Code_5_8.out ${GCCFLAG} Code_5_8.c
Code_5_9: Code_5_9.c
	gcc -o Code_5_9.out ${GCCFLAG} Code_5_9.c
Code_5_10: Code_5_10.c
	gcc -o Code_5_10.out ${GCCFLAG} Code_5_10.c
Code_5_11: Code_5_11.c
	gcc -o Code_5_11.out ${GCCFLAG} Code_5_11.c




.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
