objects:=*.out *.o
GCCFALG:=-Wall -W -O2

remind: remind.c
	gcc -o remind.out ${GCCFALG} remind.c
planet: planet.c
	gcc -o planet.out ${GCCFALG} planet.c
print_char: print_char.c
	gcc -o print_char.out ${GCCFALG} print_char.c
Ex_13_3: Ex_13_3.c
	gcc -o Ex_13_3.out ${GCCFALG} Ex_13_3.c
Ex_13_5a: Ex_13_5a.c
	gcc -o Ex_13_5a.out ${GCCFALG} Ex_13_5a.c
Ex_13_5b: Ex_13_5b.c
	gcc -o Ex_13_5b.out ${GCCFALG} Ex_13_5b.c
Ex_13_6: Ex_13_6.c
	gcc -o Ex_13_6.out ${GCCFALG} Ex_13_6.c
Ex_13_9: Ex_13_9.c
	gcc -o Ex_13_9.out ${GCCFALG} Ex_13_9.c
Ex_13_11: Ex_13_11.c
	gcc -o Ex_13_11.out ${GCCFALG} Ex_13_11.c
Ex_13_12: Ex_13_12.c
	gcc -o Ex_13_12.out ${GCCFALG} Ex_13_12.c
Ex_13_13: Ex_13_13.c
	gcc -o Ex_13_13.out ${GCCFALG} Ex_13_13.c
Ex_13_14: Ex_13_14.c
	gcc -o Ex_13_14.out ${GCCFALG} Ex_13_14.c
Ex_13_15: Ex_13_15.c
	gcc -o Ex_13_15.out ${GCCFALG} Ex_13_15.c
Ex_13_16: Ex_13_16.c
	gcc -o Ex_13_16.out ${GCCFALG} Ex_13_16.c
Ex_13_17: Ex_13_17.c
	gcc -o Ex_13_17.out ${GCCFALG} Ex_13_17.c
Ex_13_18: Ex_13_18.c
	gcc -o Ex_13_18.out ${GCCFALG} Ex_13_18.c
Code_13_1: Code_13_1.c
	gcc -o Code_13_1.out ${GCCFALG} Code_13_1.c
Code_13_2: Code_13_2.c
	gcc -o Code_13_2.out ${GCCFALG} Code_13_2.c
Code_13_3: Code_13_3.c
	gcc -o Code_13_3.out ${GCCFALG} Code_13_3.c
Code_13_4: Code_13_4.c
	gcc -o Code_13_4.out ${GCCFALG} Code_13_4.c
Code_13_5: sum.c
	gcc -o sum.out ${GCCFALG} sum.c
Code_13_6: Code_13_6.c
	gcc -o Code_13_6.out ${GCCFALG} Code_13_6.c
Code_13_7: Code_13_7.c
	gcc -o Code_13_7.out ${GCCFALG} Code_13_7.c
Code_13_8: Code_13_8.c
	gcc -o Code_13_8.out ${GCCFALG} Code_13_8.c
Code_13_9: Code_13_9.c
	gcc -o Code_13_9.out ${GCCFALG} Code_13_9.c
Code_13_10: Code_13_10.c
	gcc -o Code_13_10.out ${GCCFALG} Code_13_10.c
Code_13_11: Code_13_11.c
	gcc -o Code_13_11.out ${GCCFALG} Code_13_11.c
Code_13_12: Code_13_12.c
	gcc -o Code_13_12.out ${GCCFALG} Code_13_12.c
Code_13_13: Code_13_13.c
	gcc -o Code_13_13.out ${GCCFALG} Code_13_13.c
Code_13_14: Code_13_14.c
	gcc -o Code_13_14.out ${GCCFALG} Code_13_14.c
Code_13_15: Code_13_15.c
	gcc -o Code_13_15.out ${GCCFALG} Code_13_15.c
Code_13_16: Code_13_16.c
	gcc -o Code_13_16.out ${GCCFALG} Code_13_16.c
Code_13_17: Code_13_17.c
	gcc -o Code_13_17.out ${GCCFALG} Code_13_17.c
Code_13_18: Code_13_18.c
	gcc -o Code_13_18.out ${GCCFALG} Code_13_18.c



.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
