objects:=*.out *.o
GCCFLAG:=-Wall -W -O2

tprintf: tprintf.c
	gcc -o tprintf.out ${GCCFLAG} tprintf.c
addfrac: addfrac.c
	gcc -o addfrac.out ${GCCFLAG} addfrac.c
Ex_3_1: Ex_3_1.c
	gcc -o Ex_3_1.out ${GCCFLAG} Ex_3_1.c
Ex_3_2: Ex_3_2.c
	gcc -o Ex_3_2.out ${GCCFLAG} Ex_3_2.c
Ex_3_4: Ex_3_4.c
	gcc -o Ex_3_4.out ${GCCFLAG} Ex_3_4.c
Ex_3_5: Ex_3_5.c
	gcc -o Ex_3_5.out ${GCCFLAG} Ex_3_5.c
Ex_3_6: Ex_3_6.c
	gcc -o Ex_3_6.out ${GCCFLAG} Ex_3_6.c
Code3_1: Code3_1.c
	gcc -o Code3_1.out ${GCCFLAG} Code3_1.c
Code3_2: Code3_2.c
	gcc -o Code3_2.out ${GCCFLAG} Code3_2.c
Code3_3: Code3_3.c
	gcc -o Code3_3.out ${GCCFLAG} Code3_3.c
Code3_4: Code3_4.c
	gcc -o Code3_4.out ${GCCFLAG} Code3_4.c
Code3_5: Code3_5.c
	gcc -o Code3_5.out ${GCCFLAG} Code3_5.c
Code3_6: Code3_6.c
	gcc -o Code3_6.out ${GCCFLAG} Code3_6.c
	




.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
