objects:=*.out *.o *.so
GCCFALG:=-Wall -W -O2

22_2: 22_2.c
	gcc -o 22_2.out ${GCCFALG} 22_2.c
canopen: canopen.c
	gcc -o canopen.out ${GCCFALG} canopen.c
22_3: 22_3.c
	gcc -o 22_3.out ${GCCFALG} 22_3.c
22_3_10: 22_3_10.c
	gcc -o 22_3_10.out ${GCCFALG} 22_3_10.c
22_4: 22_4.c
	gcc -o 22_4.out ${GCCFALG} 22_4.c
fcopy: fcopy.c
	gcc -o fcopy.out ${GCCFALG} fcopy.c
invclear: invclear.c
	gcc -o invclear.out ${GCCFALG} invclear.c
Ex_22_4: Ex_22_4.c
	gcc -o Ex_22_4.out ${GCCFALG} Ex_22_4.c
Ex_22_6: Ex_22_6.c
	gcc -o Ex_22_6.out ${GCCFALG} Ex_22_6.c
Ex_22_7: Ex_22_7.c
	gcc -o Ex_22_7.out ${GCCFALG} Ex_22_7.c
Ex_22_10: Ex_22_10.c
	gcc -o Ex_22_10.out ${GCCFALG} Ex_22_10.c
Ex_22_13: Ex_22_13.c
	gcc -o Ex_22_13.out ${GCCFALG} Ex_22_13.c
Code_22_1: Code_22_1.c
	gcc -o Code_22_1.out ${GCCFALG} Code_22_1.c
Code_22_2: Code_22_2.c
	gcc -o Code_22_2.out ${GCCFALG} Code_22_2.c
Code_22_3: Code_22_3.c
	gcc -o Code_22_3.out ${GCCFALG} Code_22_3.c
Code_22_4_a: Code_22_4_a.c
	gcc -o Code_22_4_a.out ${GCCFALG} Code_22_4_a.c
Code_22_4_b: Code_22_4_b.c
	gcc -o Code_22_4_b.out ${GCCFALG} Code_22_4_b.c
Code_22_4_c: Code_22_4_c.c
	gcc -o Code_22_4_c.out ${GCCFALG} Code_22_4_c.c
Code_22_5: Code_22_5.c
	gcc -o Code_22_5.out ${GCCFALG} Code_22_5.c
Code_22_6: Code_22_6.c
	gcc -o Code_22_6.out ${GCCFALG} Code_22_6.c
Code_22_9: Code_22_9.c
	gcc -o Code_22_9.out ${GCCFALG} Code_22_9.c
Code_22_11: Code_22_11.c
	gcc -o Code_22_11.out ${GCCFALG} Code_22_11.c
Code_22_12: Code_22_12.c
	gcc -o Code_22_12.out ${GCCFALG} Code_22_12.c
Code_22_14: Code_22_14.c
	gcc -o Code_22_14.out ${GCCFALG} Code_22_14.c
Code_22_16: Code_22_16.c
	gcc -o Code_22_16.out ${GCCFALG} Code_22_16.c
Code_22_17: Code_22_17.c
	gcc -o Code_22_17.out ${GCCFALG} Code_22_17.c


.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done


