objects:=*.out *.o
GCCFALG:=-Wall -W -O2

average: average.c
	gcc -o average.out ${GCCFALG} average.c
countdown: countdown.c
	gcc -o countdown.out ${GCCFALG} countdown.c
pun2: pun2.c
	gcc -o pun2.out ${GCCFALG} pun2.c
prime: prime.c
	gcc -o prime.out ${GCCFALG} prime.c
qsort: qsort.c
	gcc -o qsort.out ${GCCFALG} qsort.c
Ex_9_2: Ex_9_2.c
	gcc -o Ex_9_2.out ${GCCFALG} Ex_9_2.c
Ex_9_5: Ex_9_5.c
	gcc -o Ex_9_5.out ${GCCFALG} Ex_9_5.c
Ex_9_6: Ex_9_6.c
	gcc -o Ex_9_6.out ${GCCFALG} Ex_9_6.c
Ex_9_11: Ex_9_11.c
	gcc -o Ex_9_11.out ${GCCFALG} Ex_9_11.c



iPHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
