objects:=*.out *.o
GCCFALG:=-Wall -W -O2

average: average.c
	gcc -o average.out ${GCCFALG} average.c
countdown: countdown.c
	gcc -o countdown.out ${GCCFALG} countdown.c
pun2: pun2.c
	gcc -o pun2.out ${GCCFALG} pun2.c
prime: prime.c
	gcc -o prime.out ${GCCFALG} prime.c
qsort: qsort.c
	gcc -o qsort.out ${GCCFALG} qsort.c
Ex_9_2: Ex_9_2.c
	gcc -o Ex_9_2.out ${GCCFALG} Ex_9_2.c
Ex_9_5: Ex_9_5.c
	gcc -o Ex_9_5.out ${GCCFALG} Ex_9_5.c
Ex_9_6: Ex_9_6.c
	gcc -o Ex_9_6.out ${GCCFALG} Ex_9_6.c
Ex_9_11: Ex_9_11.c
	gcc -o Ex_9_11.out ${GCCFALG} Ex_9_11.c
Ex_9_18: Ex_9_18.c
	gcc -o Ex_9_18.out ${GCCFALG} Ex_9_18.c
Ex_9_19: Ex_9_19.c
	gcc -o Ex_9_19.out ${GCCFALG} Ex_9_19.c
Code_9_1: Code_9_1.c
	gcc -o Code_9_1.out ${GCCFALG} Code_9_1.c
Code_9_2: Code_9_2.c
	gcc -o Code_9_2.out ${GCCFALG} Code_9_2.c
Code_9_3: Code_9_3.c
	gcc -o Code_9_3.out ${GCCFALG} Code_9_3.c
Code_9_4: Code_9_4.c
	gcc -o Code_9_4.out ${GCCFALG} Code_9_4.c
Code_9_5: Code_9_5.c
	gcc -o Code_9_5.out ${GCCFALG} Code_9_5.c
Code_9_6: Code_9_6.c
	gcc -o Code_9_6.out ${GCCFALG} Code_9_6.c
Code_9_7: Code_9_7.c
	gcc -o Code_9_7.out ${GCCFALG} Code_9_7.c
Code_9_8: Code_9_8.c
	gcc -o Code_9_8.out ${GCCFALG} Code_9_8.c



.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
