objects:=*.out *.o

pun: pun.c
	gcc -o pun.out -O2 pun.c
dweight: dweight.c
	gcc -o dweight.out -O2 dweight.c
dweight2: dweight2.c
	gcc -o dweight2.out -O2 dweight2.c
celsius: celsius.c
	gcc -o celsius.out -O2 celsius.c
Ex_2_1: Ex_2_1.c
	gcc -o Ex_2_1.out -Wall -W -O2 Ex_2_1.c
Ex_2_2: Ex_2_2.c
	gcc -o Ex_2_2.out -Wall -W -O2 Ex_2_2.c
Ex_2_3: Ex_2_3.c
	gcc -o Ex_2_3.out -Wall -W -O2 Ex_2_3.c
Ex_2_4: Ex_2_4.c
	gcc -o Ex_2_4.out -Wall -W -O2 Ex_2_4.c
code1: code1.c
	gcc -o code1.out -Wall -W -O2 code1.c
code2: code2.c
	gcc -o code2.out -Wall -W -O2 code2.c
code3: code3.c
	gcc -o code3.out -Wall -W -O2 code3.c
code4: code4.c
	gcc -o code4.out -Wall -W -O2 code4.c
code5: code5.c
	gcc -o code5.out -Wall -W -O2 code5.c
code6: code6.c
	gcc -o code6.out -Wall -W -O2 code6.c
code7: code7.c
	gcc -o code7.out -Wall -W -O2 code7.c
code8: code8.c
	gcc -o code8.out -Wall -W -O2 code8.c
	




.PHONY: clean
	clean:
	-rm edit ${objects}
	echo Clean done
