objects:=*.out *.o
GCCFALG:=-Wall -W -O2

struct_demo: struct_demo.c
	gcc -o struct_demo.out ${GCCFALG} struct_demo.c
Ex_16_1: Ex_16_1.c
	gcc -o Ex_16_1.out ${GCCFALG} Ex_16_1.c
Ex_16_2: Ex_16_2.c
	gcc -o Ex_16_2.out ${GCCFALG} Ex_16_2.c
Ex_16_3: Ex_16_3.c
	gcc -o Ex_16_3.out ${GCCFALG} Ex_16_3.c
Ex_16_4: Ex_16_4.c
	gcc -o Ex_16_4.out ${GCCFALG} Ex_16_4.c
Ex_16_5: Ex_16_5.c
	gcc -o Ex_16_5.out ${GCCFALG} Ex_16_5.c
Ex_16_6: Ex_16_6.c
	gcc -o Ex_16_6.out ${GCCFALG} Ex_16_6.c
Ex_16_7: Ex_16_7.c
	gcc -o Ex_16_7.out ${GCCFALG} Ex_16_7.c
Ex_16_8: Ex_16_8.c
	gcc -o Ex_16_8.out ${GCCFALG} Ex_16_8.c
Ex_16_9: Ex_16_9.c
	gcc -o Ex_16_9.out ${GCCFALG} Ex_16_9.c
Ex_16_10: Ex_16_10.c
	gcc -o Ex_16_10.out ${GCCFALG} Ex_16_10.c
Ex_16_14: Ex_16_14.c
	gcc -o Ex_16_14.out ${GCCFALG} Ex_16_14.c
Ex_16_20: Ex_16_20.c
	gcc -o Ex_16_20.out ${GCCFALG} Ex_16_20.c
Code_16_1: Code_16_1.c
	gcc -o Code_16_1.out ${GCCFALG} Code_16_1.c


.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done


