objects:=*.out *.o
GCCFALG:=-Wall -W -O2

reverse: reverse.c
	gcc -o reverse.out ${GCCFALG} reverse.c
arrayinit: arrayinit.c
	gcc -o arrayinit.out ${GCCFALG} arrayinit.c
repdigit: repdigit.c
	gcc -o repdigit.out ${GCCFALG} repdigit.c
interest: interest.c
	gcc -o interest.out ${GCCFALG} interest.c
deal: deal.c
	gcc -o deal.out ${GCCFALG} deal.c
reverse2: reverse2.c
	gcc -o reverse2.out ${GCCFALG} reverse2.c
Ex_8_3: Ex_8_3.c
	gcc -o Ex_8_3.out ${GCCFALG} Ex_8_3.c
Ex_8_5: Ex_8_5.c
	gcc -o Ex_8_5.out ${GCCFALG} Ex_8_5.c
Ex_8_11: Ex_8_11.c
	gcc -o Ex_8_11.out ${GCCFALG} Ex_8_11.c
Code_8_1: Code_8_1.c
	gcc -o Code_8_1.out ${GCCFALG} Code_8_1.c
Code_8_2: Code_8_2.c
	gcc -o Code_8_2.out ${GCCFALG} Code_8_2.c
Code_8_3: Code_8_3.c
	gcc -o Code_8_3.out ${GCCFALG} Code_8_3.c
Code_8_4: Code_8_4.c
	gcc -o Code_8_4.out ${GCCFALG} Code_8_4.c
Code_8_5: Code_8_5.c
	gcc -o Code_8_5.out ${GCCFALG} Code_8_5.c
Code_8_6: Code_8_6.c
	gcc -o Code_8_6.out ${GCCFALG} Code_8_6.c
Code_8_7: Code_8_7.c
	gcc -o Code_8_7.out ${GCCFALG} Code_8_7.c
Code_8_8: Code_8_8.c
	gcc -o Code_8_8.out ${GCCFALG} Code_8_8.c
Code_8_9: Code_8_9.c
	gcc -o Code_8_9.out ${GCCFALG} Code_8_9.c
Code_8_11: Code_8_11.c
	gcc -o Code_8_11.out ${GCCFALG} Code_8_11.c
Code_8_12: Code_8_12.c
	gcc -o Code_8_12.out ${GCCFALG} Code_8_12.c
Code_8_13: Code_8_13.c
	gcc -o Code_8_13.out ${GCCFALG} Code_8_13.c
Code_8_14: Code_8_14.c
	gcc -o Code_8_14.out ${GCCFALG} Code_8_14.c
Code_8_15: Code_8_15.c
	gcc -o Code_8_15.out ${GCCFALG} Code_8_15.c
Code_8_16: Code_8_16.c
	gcc -o Code_8_16.out ${GCCFALG} Code_8_16.c
Code_8_17: Code_8_17.c
	gcc -o Code_8_17.out ${GCCFALG} Code_8_17.c






.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
