objects:=*.out *.o
GCCFALG:=-Wall -W -O2

reverse: reverse.c
	gcc -o reverse.out ${GCCFALG} reverse.c
arrayinit: arrayinit.c
	gcc -o arrayinit.out ${GCCFALG} arrayinit.c
repdigit: repdigit.c
	gcc -o repdigit.out ${GCCFALG} repdigit.c
interest: interest.c
	gcc -o interest.out ${GCCFALG} interest.c
deal: deal.c
	gcc -o deal.out ${GCCFALG} deal.c
reverse2: reverse2.c
	gcc -o reverse2.out ${GCCFALG} reverse2.c
Ex_8_3: Ex_8_3.c
	gcc -o Ex_8_3.out ${GCCFALG} Ex_8_3.c
Ex_8_5: Ex_8_5.c
	gcc -o Ex_8_5.out ${GCCFALG} Ex_8_5.c
Ex_8_11: Ex_8_11.c
	gcc -o Ex_8_11.out ${GCCFALG} Ex_8_11.c
Code_8_1: Code_8_1.c
	gcc -o Code_8_1.out ${GCCFALG} Code_8_1.c
Code_8_2: Code_8_2.c
	gcc -o Code_8_2.out ${GCCFALG} Code_8_2.c
Code_8_3: Code_8_3.c
	gcc -o Code_8_3.out ${GCCFALG} Code_8_3.c
Code_8_4: Code_8_4.c
	gcc -o Code_8_4.out ${GCCFALG} Code_8_4.c
Code_8_5: Code_8_5.c
	gcc -o Code_8_5.out ${GCCFALG} Code_8_5.c






.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
