objects:=*.out *.o
GCCFALG:=-Wall -W -O2

guess: guess.c
	gcc -o guess.out ${GCCFALG} guess.c
guess2: guess2.c
	gcc -o guess2.out ${GCCFALG} guess2.c
poker: poker.c
	gcc -o poker.out ${GCCFALG} poker.c
Code_10_1: Code_10_1.c
	gcc -o Code_10_1.out ${GCCFALG} Code_10_1.c
Code_10_2: Code_10_2.c
	gcc -o Code_10_2.out ${GCCFALG} Code_10_2.c
Code_10_3: Code_10_3.c
	gcc -o Code_10_3.out ${GCCFALG} Code_10_3.c
Code_10_4: Code_10_4.c
	gcc -o Code_10_4.out ${GCCFALG} Code_10_4.c
Code_10_5: Code_10_5.c
	gcc -o Code_10_5.out ${GCCFALG} Code_10_5.c
Code_10_6: Code_10_6.c
	gcc -o Code_10_6.out ${GCCFALG} Code_10_6.c
Code_10_7: Code_10_7.c
	gcc -o Code_10_7.out ${GCCFALG} Code_10_7.c


iPHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
