objects:=*.out *.o
GCCFALG:=-Wall -W -O2

reverse3: reverse3.c
	gcc -o reverse3.out ${GCCFALG} reverse3.c
Ex_12_3: Ex_12_3.c
	gcc -o Ex_12_3.out ${GCCFALG} Ex_12_3.c
Ex_12_5: Ex_12_5.c
	gcc -o Ex_12_5.out ${GCCFALG} Ex_12_5.c
Ex_12_7: Ex_12_7.c
	gcc -o Ex_12_7.out ${GCCFALG} Ex_12_7.c
Ex_12_9: Ex_12_9.c
	gcc -o Ex_12_9.out ${GCCFALG} Ex_12_9.c



iPHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
