objects:=*.out *.o
GCCFALG:=-Wall -W -O2

reverse3: reverse3.c
	gcc -o reverse3.out ${GCCFALG} reverse3.c
Ex_12_3: Ex_12_3.c
	gcc -o Ex_12_3.out ${GCCFALG} Ex_12_3.c
Ex_12_5: Ex_12_5.c
	gcc -o Ex_12_5.out ${GCCFALG} Ex_12_5.c
Ex_12_7: Ex_12_7.c
	gcc -o Ex_12_7.out ${GCCFALG} Ex_12_7.c
Ex_12_9: Ex_12_9.c
	gcc -o Ex_12_9.out ${GCCFALG} Ex_12_9.c
Ex_12_10: Ex_12_10.c
	gcc -o Ex_12_10.out ${GCCFALG} Ex_12_10.c
Ex_12_11: Ex_12_11.c
	gcc -o Ex_12_11.out ${GCCFALG} Ex_12_11.c
Ex_12_12: Ex_12_12.c
	gcc -o Ex_12_12.out ${GCCFALG} Ex_12_12.c
Ex_12_13: Ex_12_13.c
	gcc -o Ex_12_13.out ${GCCFALG} Ex_12_13.c
Ex_12_14: Ex_12_14.c
	gcc -o Ex_12_14.out ${GCCFALG} Ex_12_14.c
Ex_12_17: Ex_12_17.c
	gcc -o Ex_12_17.out ${GCCFALG} Ex_12_17.c
Code_12_1: Code_12_1.c
	gcc -o Code_12_1.out ${GCCFALG} Code_12_1.c
Code_12_1a: Code_12_1a.c
	gcc -o Code_12_1a.out ${GCCFALG} Code_12_1a.c
Code_12_2a: Code_12_2a.c
	gcc -o Code_12_2a.out ${GCCFALG} Code_12_2a.c
Code_12_2b: Code_12_2b.c
	gcc -o Code_12_2b.out ${GCCFbLG} Code_12_2b.c
Code_12_3: Code_12_3.c
	gcc -o Code_12_3.out ${GCCFbLG} Code_12_3.c
Code_12_5: Code_12_5.c
	gcc -o Code_12_5.out ${GCCFbLG} Code_12_5.c
Code_12_6: Code_12_6.c
	gcc -o Code_12_6.out ${GCCFbLG} Code_12_6.c
Code_12_7: Code_12_7.c
	gcc -o Code_12_7.out ${GCCFbLG} Code_12_7.c



.PHONY: clean
clean:
	-rm edit ${objects}
	echo Clean done
